name: Build example-app

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - main

defaults:
  run:
    working-directory: example-app

jobs:
  # Create example-app build for Android
  build-apk:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      # Setup Web environment to install packages.
      - name: Setup Web environment
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      # Setup Java environment in order to build the Android app.
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          add-job-summary: 'on-failure'

      - name: Install plugin packages
        working-directory: .
        run: npm ci

      - name: Build the plugin
        working-directory: .
        run: npm run build

      - name: Install example-app packages
        run: npm ci

      - name: Build the example-app project
        run: npm run build

      - name: Sync to copy web assets into the platform
        run: npx cap sync android

      - name: Build Android debug APK
        working-directory: example-app/android
        run: ./gradlew assembleDebug

      - name: Save apk file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cap_safearea_plugin_example_android
          path: example-app/android/app/build/outputs/apk/debug/app-debug.apk

  # Build iOS .app build that can drag and dropped into a iOS simulator
  build-ios-simulator:
    name: Create an iOS Simulator build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      # Setup Web environment to install packages.
      - name: Setup Web environment
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Restore Pods cache
        uses: actions/cache@v4
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: ${{ runner.os }}-pods-

      - name: Install plugin packages
        working-directory: .
        run: npm ci

      - name: Build the plugin
        working-directory: .
        run: npm run build

      - name: Install example-app packages
        run: npm ci

      - name: Build the example-app project
        run: npm run build

      - name: Sync to copy web assets into the platform
        run: npx cap sync ios

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Run simulator build command
        working-directory: example-app/ios/App
        run: |
          set -o pipefail
          xcodebuild \
          -scheme App \
          -workspace App.xcworkspace \
          -sdk iphonesimulator \
          -configuration Release \
          -derivedDataPath build | xcpretty

      - name: Store build .app file as zip
        working-directory: example-app/ios/App
        run: |
          cd build/Build/Products/Release-iphonesimulator
          mv App.app safearea_plugin_example_ios.app
          mkdir -p output
          zip -r -y -o output/safearea_plugin_example_ios.zip safearea_plugin_example_ios.app

      - name: Save build file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cap_safearea_plugin_example_ios
          path: example-app/ios/App/build/Build/Products/Release-iphonesimulator/output